name: "🐞 Bug Report"
description: "Report a problem, error, or unexpected behavior on pubx.dev."
title: "[BUG] A short, descriptive title"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for reporting a bug!**
        Please fill out this form with as much detail as possible so we can quickly investigate and fix the problem.
  - type: input
    id: summary
    attributes:
      label: "Brief summary of the bug"
      description: "In one sentence, what’s going wrong?"
      placeholder: "Example: Package search returns empty results for valid queries"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "Describe the problem in detail. What did you expect to happen, and what actually happened?"
      placeholder: |-
        Example:
        - I searched for 'http'.
        - Expected: List of packages including 'http'.
        - Actual: No results shown.
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: "Steps to reproduce"
      description: "How can we re-create the problem? List step-by-step instructions."
      placeholder: |-
        Example:
        1. Go to the home page
        2. Type 'http' in the search box
        3. Press Enter
        4. See error
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: "Browser/Device & Version"
      description: "What browser and device were you using? (If relevant, include OS version)"
      placeholder: "Example: Chrome 120 on Windows 11, iPhone Safari"
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots or logs (optional)"
      description: "Paste any error messages, screenshots, or log output that could help us understand the issue."
  - type: textarea
    id: extra
    attributes:
      label: "Additional context (optional)"
      description: "Any other information that might help? (e.g. account info, links, timing, etc.)"