name: "❓ Question / Support"
description: "Ask a question or get help with pubx.dev features."
title: "[QUESTION] A short, descriptive title"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        **Need help or have a question about pubx.dev?**
        Please describe what you’d like to know or the issue you’re facing. The more detail you provide, the faster we can help!
  - type: input
    id: summary
    attributes:
      label: "Your question or support topic"
      description: "Summarize your question or issue in one sentence."
      placeholder: "Example: How do I compare two packages side by side?"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "Describe your question or problem as clearly as possible. What have you tried so far?"
      placeholder: |-
        Example:
        - I want to compare 'http' and 'dio' packages.
        - Is there a way to see their health scores and features side by side?
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: "Additional information (optional)"
      description: "Add any screenshots, links, or context that might help us answer your question faster."