name: Auto-close Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Close PR and comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              state: "closed"
            });
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "Thank you for your interest! This repository does not accept pull requests. Please use issues for support, bug reports, or feature requests."
            });
